str1 = """>Rosalind_0323
CGCGTTGCAGCTAGAACGACCGAAACGCTTTTGATGGACGCAGACACAAATGGAGTTTCA\
GCCCACTAACTGATCAGTGGGTAATGATAGGAGGAGCAGGGTTGCGTCTCATCACTTGTT\
GTATGGAGACGACAGAACGTGAGTTTGGATTTTGCATCTACACTAGTTGATGGCTCTCGT\
TGGCCGTGAGTGTAAGAGGGTGCTTCATAACGTGACTTTCGCAAAGGGATCACTACTCGT\
AGCGCCTAAGTGGGGCAAGTGGAGCACAAAAGTCGTACAGCGGCACCCCATAGCCCAGTC\
ACAATGGAATCAGTGTGACATCTCCATGATAGAGGCACGAGACCCATACGATTCAGAAAT\
GCGGTAGCAACCTGCCTACTCTAATGGACTTTGGTACACTGGAGTGCGTCCCTTTTTATA\
ATCTCCCTAGGAACCTATATTGTCAAATAGCCGCGCTACGTACGTAGTGGGCGGAAGCTT\
GTCTGTTTCCGGCGGAATGCCCTTTTCGAATATGATCCCCTGCTGATTCCTTTGATTACG\
TAGGGAGAGCGCAAGCTACGTGTAAGTGAGGGGATCCCATGCGATGATTGACACACTTTA\
GCGAGGACTCTAGTAAACTCCCACTTGCTGTACTCACATGCGTAGGGCTGTTCGTGCGGT\
TCTGGGACTTCCTTGCGGGAGCTCACACTTTGAGAGTGGGAGTGCAGCGTTAGACTACGG\
TACGGAAGTAAACATGGCAGCGCGGATCTTCTCACTCAGGTACTTCGAGTAACTGAGCGG\
GGACCACTTGGGCTTCCACGAGTTGCCACTATGTCCAAGAACTGCGAATCGACGAGATCG\
CCCTTATTCCATTACCCCCCGCCGTCTTTCCCGTACTTTCGGTGAGAGTGATACGGGAAC\
CCACAGGAGCATGGTCCGATAT"""

data = str1.split("\n")[1]

dict = {"C": "G",
		"G": "C",
		"T": "A",
		"A": "T"}

for i in range(len(data)):
	for l in range(4,13):
		test_str = data[i:i+l]
		if len(test_str) == l:
			comp_str = [dict[k] for k in test_str]
			comp_str = ''.join(comp_str)[::-1]
			if test_str == comp_str:
				print("%s %s" %(i+1,l))